#include "cNeigungssensor.h"
#include "MeasurementLog.h"
#include "cWiFiKommunikation.h"
#include "cGyroansteuerung.h"
#include "cLenkermotoransteuerung.h"
//#include "cLenkersensor.h"
#include "cStatusLog.h"
#include "cSingleton.h"